#!/usr/bin/env bash
set -euo pipefail

repo_root="$(CDPATH= cd -- "$(dirname "$0")" && pwd)"
export PYTHONDONTWRITEBYTECODE=1

# Keep this entrypoint stable. The individual suites live under tests/harness/
# so subsystem checks can grow without turning this file into a monolith again.
source "$repo_root/tests/harness/lib.sh"
source "$repo_root/tests/harness/static-install.sh"
source "$repo_root/tests/harness/adapter-sync.sh"
source "$repo_root/tests/harness/doc-consistency.sh"
source "$repo_root/tests/harness/template-sync.sh"
source "$repo_root/tests/harness/verification-modes.sh"
source "$repo_root/tests/harness/scope.sh"
source "$repo_root/tests/harness/policy.sh"
source "$repo_root/tests/harness/task-validation.sh"
source "$repo_root/tests/harness/command-runner.sh"
source "$repo_root/tests/harness/command-ledger.sh"
source "$repo_root/tests/harness/episode.sh"
source "$repo_root/tests/harness/acceptance-review.sh"
source "$repo_root/tests/harness/evidence-bind.sh"
source "$repo_root/tests/harness/task-profile.sh"
source "$repo_root/tests/harness/architecture-evidence.sh"
source "$repo_root/tests/harness/architecture-sensors.sh"
source "$repo_root/tests/harness/failure-attribution.sh"
source "$repo_root/tests/harness/interventions.sh"
source "$repo_root/tests/harness/sandbox-evidence.sh"
source "$repo_root/tests/harness/sandbox-runner.sh"
source "$repo_root/tests/harness/sandbox-ci-smoke.sh"
source "$repo_root/tests/harness/release-integrity.sh"
source "$repo_root/tests/harness/release-upgrade.sh"
source "$repo_root/tests/harness/rag-adoption.sh"
source "$repo_root/tests/harness/repo-verification.sh"
source "$repo_root/tests/harness/verification-lifecycle.sh"
source "$repo_root/tests/harness/finish-examples.sh"
source "$repo_root/tests/harness/resource-envelope.sh"
source "$repo_root/tests/harness/finish-runtime-modules.sh"
source "$repo_root/tests/harness/entropy-audit.sh"
source "$repo_root/tests/harness/productization-examples.sh"
